### PR TITLE
Added tr_TR

### PR DESCRIPTION
**Pull request by bhctsntrk**

### CODE REVIEW

**Comment by bhctsntrk** [comment]
I used "ı ş ğ ü ö" instead of  "i s g u o" .

**Comment by mkzero** [comment]
@bhctsntrk is there any reason not to use the unicode characters?

**Comment by bhctsntrk** [comment]
They make trouble sometimes in python. But if you want I can use them.

**Comment by mkzero** [comment]
They shouldn't make any trouble in Python3 or with

**Pull request merged**
